name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          base-devel

    - name: Generate configure script
      run: |
        pacman -S --noconfirm autoconf automake
        aclocal
        autoconf
        automake --add-missing
      shell: msys2 {0}

    - name: Configure
      run: ./configure
      shell: msys2 {0}

    - name: Install dependencies
      run: make
      shell: msys2 {0}

    - name: Run check
      run: make check
      shell: msys2 {0}

    - name: Run distcheck
      run: make distcheck
      shell: msys2 {0}
